CREATE TABLE IF NOT EXISTS USER(user_id IDENTITY PRIMARY KEY, password VARCHAR(20));
CREATE TABLE IF NOT EXISTS USER_INFO(user_id IDENTITY PRIMARY KEY, user_name VARCHAR(50), user_email VARCHAR(50),
  first_name VARCHAR(50), second_name VARCHAR(50));
CREATE TABLE IF NOT EXISTS USER_SESSION(session_id IDENTITY PRIMARY KEY, user_id BIGINT, created_on TIMESTAMP,
  expires_on TIMESTAMP, is_valid BOOLEAN);
ALTER TABLE USER_INFO ADD CONSTRAINT NAME_UNIQUE UNIQUE(user_name);
ALTER TABLE USER_INFO ADD CONSTRAINT EMAIL_UNIQUE UNIQUE(user_email);